server:
  port: 8081

spring:
  application:
    name: ms-student


  datasource:
    url: jdbc:postgresql://localhost:5432/ms-students_db
    username: postgres
    password: mehdi
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

message:
  info: "Configuration MS Students depuis Git"
